# Ender 2 Pro X-Axis Carriage Designs
## Original X Carriage Design Prompt

```
Using OpenSCAD code model the Ender 2 Pro X Axis Carriage Plate. This plate was originally made of a single stamped metal plate wit ha single bend and with two inserts to produce stand-offs to hold the standard Ender heat-sink and hot-end assembly.

Here is the break down of each component and relevant measurements:
  - The plate section excluding the bent forked parts of the model and the eyelet measures at 61.25mm across and 45.30 down. When considering the length including the eyelet its 61.25mm across and 64.00mm down.
  - The thickness of the plate is 2.50mm.
  - The forks are bent 90 degrees from the rest of the plate and have a matching length of 20.38mm.
  - The left fork when looking at the plate from the back (fork pointing towards the viewer) is 13.50mm wide with a gap from the top edge down 10.50mm with a width of 1.75mm. The gap is 6.90mm from the left side of the fork and 4.85mm from the right side of the fork
  - The right fork when looking at the plate from the back (fork pointing towards the viewer) is 11.50mm wide with a gap from the top edge down 10.50mm with a width of 1.75mm. The gap is 4.90mm from the left side of the fork and 4.85mm from the right side of the fork
  - The eyelet sits between the two forks and is 24.04mm wide. It has a hole in the centre which is 7.10mm in diameter. There is a gap of 5.25mm from the right edge of the left fork (13.50mm fork) to the eyelet. There is another gap of 5.6mm from the left edge of the right fork (11.50mm fork). This eyelet sticks out the bottom of the plate and has a hole 8.5mm from the bottom and 8.5mm from either side as its centered in the middle of the eyelet. The eyelet is rounded towards from bottom half of the hole.
  - The left side of the plate has two notches. The notch closest to the bottom is 4.20mm from the boot of the plate where the left fork bends 90 degrees. It has a width of 5.20mm and a depth of 2.30mm. The next notch is 13.60mm from the top of the first notch and the bottom edge of the second notch. The second notch is 5.40mm wide and 2.03mm deep.
  - The right side of the plate has one notch. It is 7.00mm from the bottom of the plate where the right fork is bent 90 degrees from the plate. The notch is 6.40mm wide and 3.04 mm deep.
  - There is a cutout rectangle with rounded edges. It is 22.00mm by 14.00mm and is 23mm from the left side of the plate. It is 28.60mm from the top of the plate.
  - There are two M3 threaded holes one above the other when looking on the front surface of the plate. They are 17.00mm from the left side of the plate. The top hole is 24.95mm from the top of the plate to the top of the hole. The second hole is 11.70mm from the bottom of the top hole and the top of the bottom hole.
  - The two stand-offs which hold the heat-sink are both M3 threaded holes as well. Each stand-off is 23.60mm from the top of the plate. The left most stand-off is 27.00 mm from the left side of the plate. The right stand-off is 11.60mm from the right side of the left stand-off to the left side of the right stand-off. The stand-offs are 5.5mm tall and the outer diameter is 4.15mm.
  - There are another two M3 holes on the other side (right side) of the plate. They are both 4.8mm from the right edge of the plate. The bottom of the top hole and the top of the bottom hole are 4.6mm from each other. The bottom of the bottom hole to the bottom of the plate (where the fork bends 90 degrees) is 17.50mm.
  - There is a 3.5mm hole near the top of the plate. It is 2.23mm from the top edge of the plate and 23.00mm from the left edge of the plate
  - There is a small rectangle hole near the top of the plate. It is 2.30mm by 3.40mm. Its 1.75mm from the top edge of the plate and 8.80mm from the right edge of the plate.
  - There are two 5.20mm holes used to hold the two V-Wheels at the top of the plate. The left hole is 9.45mm from the left edge of the plate and the right hole is 9.45mm from the right edge of the plate. They are both 9.30mm from the top of each hole to the top edge of the plate.
  - The two top corners of the plate are rounded aggressively. There is an 8.00mm from the beginning of the bevel to where the top corners of the plate would be.

Comment each component in the outputted SCAD code. Ensure that the model has high smoothness. Tabs have two spaces. Threaded holes should be a hole that is slightly smaller so it can be threaded by hand.
```


### Maybe?
Some measurements had to include thickness

### TODO
[] GitHub Workflow and compile
